png(file = "plot4.png", width = 480, height = 480, units = "px")
Sys.setlocale("LC_TIME", "American")
hpc <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?") 
onetwoFeb <- hpc[hpc$Date %in% c("1/2/2007","2/2/2007") ,]
onetwoFeb$Time <- strptime(paste(onetwoFeb$Date, onetwoFeb$Time), "%d/%m/%Y %H:%M:%S")
par(mfrow = c(2,2))
with(onetwoFeb, plot(Time,Global_active_power, type = "l",xlab = "", ylab ="Global Active Power" ))
with(onetwoFeb, plot(Time,Voltage, type = "l",xlab = "datetime", ylab ="Voltage" ))
with(onetwoFeb, plot(Time,Sub_metering_1, type = "l",xlab = "", ylab ="Energy sub metering" ))
lines(onetwoFeb$Time,onetwoFeb$Sub_metering_2, col="red")
lines(onetwoFeb$Time,onetwoFeb$Sub_metering_3, col="blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"), lty = 1, box.col = "white")
box(which = "plot", lty = 1)
with(onetwoFeb, plot(Time,Global_reactive_power, type = "l",xlab = "datetime" ))
dev.off()